### ISSUE TITLE
How to get the pretrained weights?

### ISSUE THREAD

**Issue by LLL-YUE** [NoelShin/selfmask#8]
Hello!
How can I get the pretrained weights?
I can not download them from the link provided.

**Comment by noelshin** [comment]
Dear @LLL-YUE,

Many thanks for your interests in our work.
What browsers are you currently using to download them? I've just reconfirmed that it's downloadable with Safari and Chrome (in case of Chrome, you need to use **the right click** and **save as**).

Kind regards,
Noel

**Comment by Taoww21480** [comment]
Hello, your work is very good and I am very interested in it
But I am also unable to download your pretrained weights (Google Chrome opens with garbled code and cannot be downloaded directly). Can you send me a copy of your pretrained weights via email? (My email: taoww21480@gmail.com ）Because I have trained myself and found that the effect is very poor, I would like to try your own pretrained weights. If possible, thank you very much.

**Comment by noelshin** [comment]
Dear @Taoww21480,

Thank you for your interests in our work and sorry for the late response.
Please try the following links (due to the size of files, I can't attach it to an email):

`selfmask-10-queries`: https://drive.google.com/file/d/1xDdkC3QXv9Z5z54TcBCK6M2c7byTvYn0/view?usp=share_link
`selfmask-20-queries`: https://drive.google.com/file/d/1mqA-kVPcY27thAS-4eECQw_xsSwmdksW/view?usp=share_link

Hope this works.

**Comment by Taoww21480** [comment]
@NoelShin ,
Thank you very much for your reply!
